// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// DatabaseInstance is an autogenerated mock type for the DatabaseInstance type
type DatabaseInstance struct {
	mock.Mock
}

// GetConn provides a mock function with given fields:
func (_m *DatabaseInstance) GetConn() *gorm.DB {
	ret := _m.Called()

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

// Transaction provides a mock function with given fields: _a0
func (_m *DatabaseInstance) Transaction(_a0 func() error) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(func() error) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewDatabaseInstance interface {
	mock.TestingT
	Cleanup(func())
}

// NewDatabaseInstance creates a new instance of DatabaseInstance. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDatabaseInstance(t mockConstructorTestingTNewDatabaseInstance) *DatabaseInstance {
	mock := &DatabaseInstance{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
